---
title: "データ解析の数学(C20 医療情報学 2020)"
author: "ryamada"
date: "2020年6月12日"
output: html_document
---

## はじめに

この講義(２コマ)では、
* フリーの統計ソフト「R」とそれを扱うツール「Rstudio」を使い方を覚えながら
* データ解析を実際に実行し
* データ解析の記録を残す

ことを予定していました。

対面講義形式からオンライン講義形式への変更に伴い、ハンズオンの部分を実施することが容易ではなくなりました。

ついては、「R」「Rstudio」の利用に関する部分は、オプションとし、それ以外の内容についての理解と関連課題の提出をもって受講修了とみなすことにします。

ハンズオンに相当するコンテンツには「!!オプション!!」と記して区別します。

## RとRstudioを自分のPCに設定する !!オプション!!

Rはフリーの統計解析ソフトウェア/コンピュータ言語です。

現在、大規模データの医学研究・ライフサイエンス研究では、Rと[パイソン](https://techacademy.jp/magazine/22066)とが２大言語となっています。

どちらの言語も、よく使われるデータ解析手法を実施する上では違いがありません。

もし、どちらか片方を習得するのであれば、統計学・数学の理論的背景などに興味が強ければRを、機械学習などに興味が強ければパイソンを、最初に選ぶのがよいでしょう。

Rは統計学関係者が、パイソンは情報学系関係者が、それぞれ作ってきたということが違いの背景にあります。

[こちらのリンク先](https://qiita.com/hujuu/items/ddd66ae8e6f3f989f2c0)を参考に、自身のPCにRとRstudioをインストールし、立ち上げてみましょう。

## データ解析の記録を残す (オプションではありません)

データ解析では

* 解析するデータを管理する
* データの解析をする(解析アプリケーションを使う)
* 解析アプリケーションの実行ログを記録として残す

ことを実施する必要があります。

解析データは電子ファイルやデータベースとして管理・保管します。

データの解析は、解析アプリケーションを使って実行します。Rを使うのもそのためです。

最後の解析アプリケーションの実行ログを記録として残す、という作業は、結構、厄介です。

実行の手順を、一つ一つ研究記録ノートに書き留めたり、ワープロソフトに打ち込んでファイルとして保存したりすることになります。

この講義で行うう解析の記録も、レポートとして提出することになります。

## Rマークダウン書式で記録を残す !!オプション!!

ちなみに、この講義資料はRstudioを用いてRmarkdownという方法で作成しています。

Rの実行ログがキレイに残せるメリットがあります。

レポート提出が楽になるでしょう。

Rmarkdownによるレポート作成法については[こちら](https://kohske.github.io/R/rstudio/)を参照してください。

パイソンにも同様の仕組み「[パイソンノートブック](https://techacademy.jp/magazine/17430)」があります。

## 帰無仮説検定


